### ISSUE TITLE
php 8: The track_errors ini directive has been removed

### ISSUE THREAD

**Issue by glensc** [zf1s/zf1#35]
The track_errors ini directive has been removed. This means that php_errormsg is no longer available. The error_get_last() function may be used instead.

- https://www.php.net/manual/en/migration80.incompatible.php

**Comment by Megatherium** [comment]
FYI I'm working on this. The changes are rather trivial. Writing the accompanying tests is not always as straightforward.

**Comment by Megatherium** [comment]
I just realized while finishing up: does it really make sense to have this as a separate thing if the rest of the code isn't 8.0 compatible?
[My tests pass](https://travis-ci.com/github/Megatherium/zf1/builds/207382405), well except for those for 8.0 obviously, because I branched of master and not the 8.0 compat branch.

How do we go from here? Wait till my other PR is through and then rebase?

**Comment by falkenhawk** [comment]
@Megatherium please if you could rebase on #32 or include the changes in that PR, that would be even better.

**Comment by glensc** [comment]
I personally prefer to make incremental changes, not some big ass huge PR. and therefore `allow_failure: true` must be enabled for 8.0 until it's fully ready.

**Comment by Megatherium** [comment]
Sorry for neglecting you guys. Work took over for a while.
I cherry picked the commit to fat branch (#32), PHP5.4 still failing but everything else is showing all green

**Comment by glensc** [comment]
@Megatherium no worries, seems this hurts you more than anybody else ;)

also, your PR has not been submitted, hard to guess what you're up to:
- https://github.com/zf1s/zf1/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc

**Comment by Megatherium** [comment]
I pushed the changes onto the large branch like @falkenhawk said. I have now created #42 so these changes can be reviewed separately.
